# Site settings
title: Kōan Trading - Orderflow, Market Profile, and Technical Analysis
subtitle: Personal Trading and Development Blog by Adam Li
email:
description: Personal Trading and Development Blog
tagline: Personal trading and development blog.
description: Personal trading and development blog. Market analysis, trades and trader progress reports, educational resources, and trading-related content.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://koan-trading.com" # the base hostname & protocol for your site
author: Adam Li
street_address:
city: Hong Kong
state:
zip_code:
country:
phone:
twitter:
  username: realadamli
  card: summary
logo: /assets/images/favicon.ico
lang: en_US

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url:
googleplus_url:
instagram_url: "https://instagram.com/realadamli"
linkedin_url:
pinterest_url:
slack_url:
twitter_url: "https://twitter.com/realadamli"

# Build settings
markdown: kramdown
permalink: /blog/:year:month:day/:title
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-redirect-from

whitelist:
  - jekyll-sitemap
