# Site settings
title: Kōan Trading - Order Flow, Market Profile, and Technical Analysis
subtitle: Personal Trading and Development Blog by Adam Li
email:
description: Personal Trading and Development Blog
tagline: Personal trading and development blog.
description: Personal trading and development blog. Market analysis, trades and trader progress reports, educational resources, and trading-related content.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://koan-trading.com" # the base hostname & protocol for your site
author: Adam Li
street_address:
city: Hong Kong
state:
zip_code:
country:
phone:
twitter:
  username: realadamli
  card: summary
logo: /assets/images/favicon.ico
lang: en_US

# Social settings
500px_url:
facebook_url: "https://facebook.com/realadamli"
github_url:
gitlab_url:
googleplus_url:
instagram_url: "https://instagram.com/realadamli"
linkedin_url: "https://www.linkedin.com/in/adam-li-64b22490/"
pinterest_url:
slack_url:
twitter_url: "https://twitter.com/realadamli"

# Build settings
markdown: kramdown
permalink: /blog/:categories/:year/:month/:day/:title/

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate-v2
  - jekyll-redirect-from

whitelist:
  - jekyll-sitemap

collections:
  categories:
    output: true

pagination:
  enabled: true
  per_page: 10
  sort_reverse: true
  title: ':title'
  trail:
    before: 2
    after: 2
